spring:
    application:
        name: accounts-service
    output:
      ansi:
        enabled: ALWAYS
    h2:
      console:
        enabled: true

# Service Discovery access
eureka:
    client:
      serviceUrl:
        defaultZone: http://localhost:1111/eureka

# HTTP Server
server:
  port: 0