spring:
    application:
        name: accounts-service
    output:
      ansi:
        enabled: ALWAYS
    h2:
      console:
        enabled: true

# Service Discovery access
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1111/eureka

  # The microservice instance attempts to register its presence with Eureka before this port assignment, 
  # resulting in a registration using the local IP address and a port number of zero (0), as does every subsequent 
  # instance of that microservice. This effectively restricts us to running a single instance of any local microservice 
  # we wish to register with a local Eureka instance. 
  # As a fix - we assign a unique instance-id, dynamically, to each of the instances for use by Eureka.
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}

# HTTP Server
server:
  port: ${PORT:0}

management:
  endpoints:
    web:
      exposure:
        include: "*"